name: flutter_audio_service_demo
description: Companion project for tutorial on audio_service plugin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-201.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audio_video_progress_bar: ^1.0.0
  get_it: ^7.2.0
  just_audio: ^0.9.5
  audio_service: ^0.18.9 
  shared_preferences: ^2.0.17
  dio: ^4.0.6
  path_provider: ^2.0.12
  open_file: ^3.2.1
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true